import axios from "axios";
import express from "express";
import { requireAuth } from "../middleware/auth.js";
import ResumeAnalysis from "../models/ResumeAnalysis.js";

const router = express.Router();

function fallbackResumeAnalysis(resumeText) {
  const text = resumeText.toLowerCase();
  const skills = ["javascript", "python", "sql", "excel", "communication", "leadership", "design", "marketing"].filter((skill) =>
    text.includes(skill)
  );

  return {
    matchedCareer: skills.includes("python") || skills.includes("javascript") ? "Software Developer" : "Business Analyst",
    matchScore: 0.58,
    extractedSkills: skills,
    keywords: skills,
    missingSkills: ["Portfolio projects", "Domain certification"],
    summary: "Generated by Express fallback because the ML NLP service was unavailable."
  };
}

router.post("/analyze", requireAuth, async (req, res) => {
  const resumeText = String(req.body.resumeText || "").trim();

  if (resumeText.length < 80) {
    return res.status(400).json({ message: "Paste at least 80 characters of resume content" });
  }

  let analysis;
  try {
    const ml = await axios.post(`${process.env.ML_SERVICE_URL}/analyze-resume`, { resumeText }, { timeout: 7000 });
    analysis = ml.data;
  } catch {
    analysis = fallbackResumeAnalysis(resumeText);
  }

  const saved = await ResumeAnalysis.create({
    user: req.user.id,
    resumeText,
    analysis
  });

  res.status(201).json({ analysis: saved });
});

router.get("/analyses", requireAuth, async (req, res) => {
  const analyses = await ResumeAnalysis.find({ user: req.user.id }).sort({ createdAt: -1 }).limit(20);
  res.json({ analyses });
});

export default router;

