import axios from "axios";
import express from "express";
import { questions } from "../data/questions.js";
import { requireAuth } from "../middleware/auth.js";
import TestResult from "../models/TestResult.js";

const router = express.Router();

function scoreAnswers(answers) {
  const scores = {};
  const counts = {};

  for (const question of questions) {
    let raw;
    if (question.options) {
      raw = answers[question.id] === question.correct ? 5 : 1;
    } else {
      raw = Number(answers[question.id] ?? 3);
    }
    scores[question.category] = (scores[question.category] || 0) + Math.max(1, Math.min(5, raw));
    counts[question.category] = (counts[question.category] || 0) + 1;
  }

  for (const category of Object.keys(scores)) {
    scores[category] = Math.round((scores[category] / counts[category]) * 100) / 100;
  }

  return scores;
}

function fallbackRecommendation(scores) {
  const entries = Object.entries(scores).sort((a, b) => b[1] - a[1]);
  const top = entries[0]?.[0] || "technical";
  const careerMap = {
    technical: "Software Developer",
    analytical: "Data Analyst",
    creativity: "UX Designer",
    communication: "Digital Marketing Specialist",
    social: "Career Counselor",
    business: "Business Analyst",
    health_interest: "Healthcare Professional",
    arts_interest: "Creative Media Designer",
    problem_solving: "Software Developer",
    academic_score: "Research Associate"
  };

  return {
    career: careerMap[top],
    confidence: 0.62,
    educationPath: ["Build a strong foundation", "Choose a relevant degree or certification", "Complete portfolio projects"],
    skillsToBuild: ["Communication", "Problem solving", "Digital literacy"],
    explanation: "Generated by the Express fallback because the ML service was unavailable."
  };
}

router.get("/questions", requireAuth, (_req, res) => {
  const safeQuestions = questions.map(({ correct, ...question }) => question);
  res.json({ questions: safeQuestions });
});

router.post("/submit", requireAuth, async (req, res) => {
  const answers = req.body.answers || {};
  const scores = scoreAnswers(answers);
  let recommendation;

  try {
    const ml = await axios.post(`${process.env.ML_SERVICE_URL}/predict`, { scores }, { timeout: 5000 });
    recommendation = ml.data;
  } catch {
    recommendation = fallbackRecommendation(scores);
  }

  const result = await TestResult.create({
    user: req.user.id,
    answers,
    scores,
    recommendation
  });

  res.status(201).json({ result });
});

router.get("/results", requireAuth, async (req, res) => {
  const results = await TestResult.find({ user: req.user.id }).sort({ createdAt: -1 }).limit(20);
  res.json({ results });
});

export default router;
